// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11 (migrated to 9.4.0)
// Project name: Westgate Dashboard

#include "ui.h"
#include "ecu_data.h"
#include "esp_log.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"

#include "ui_helpers.h"
#include "ui_layout_manager.h"
#include "ui_screen_manager.h"
#include "ui_updates.h"
#include "settings_config.h"


// EVENTS
lv_obj_t *ui____initial_actions0;

// TOUCH SCREEN STATE
bool touch_active = true;

///////////////////// TEST LVGL SETTINGS ////////////////////
// NOTE: These checks are disabled for EK79007 display which uses RGB888
// #if LV_COLOR_DEPTH != 16
//     #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's
//     settings"
// #endif
// #if LV_COLOR_16_SWAP !=0
//     #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's
//     settings"
// #endif

///////////////////// SCREENS ////////////////////

// Periodic LVGL timer callback to refresh gauge widgets from CAN data
static void _ui_gauge_update_timer_cb(lv_timer_t *timer) {
  (void)timer;
  update_all_gauges();
}

void ui_init(void) {
  LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

  lv_disp_t *dispp = lv_disp_get_default();
  ESP_LOGI("UI", "Default display: %p", (void *)dispp);
  if (dispp == NULL) {
    ESP_LOGE("UI", "FATAL: No display registered! ui_init cannot continue.");
    return;
  }
  // Apply theme FIRST (as in old working version) - this was the correct order
  lv_theme_t *theme = lv_theme_default_init(
      dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
      false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);

  // Initialize touch screen state
  touch_active = true;

  // Initialize screen manager
  ui_screen_manager_init();

  // Settings are already loaded in main.c, no need to load again
  // settings_load(); // REMOVED: Settings already loaded in main.c

  // Initialize all screens AFTER theme is applied (as in old working version)
  ui_Screen1_screen_init();
  ui_Screen2_screen_init(); // Add Screen2 initialization
  ui_Screen3_screen_init(); // Add Screen3 initialization
  ui_Screen4_screen_init(); // Add Screen4 initialization
  ui_Screen5_screen_init(); // Add Screen5 initialization
  ui_Screen6_screen_init(); // Add Screen6 initialization
  // Screen 7 is lazy-initialized on first switch to save LVGL heap memory
  // ui_Screen8_screen_init(); // Disabled: Causes watchdog timeout in LVGL mask
  // drawing

  ui____initial_actions0 = lv_obj_create(NULL);

  // Initialize unified layout manager and apply initial layout
  ui_layout_manager_init();

  lv_scr_load(ui_Screen1);

  // Start periodic gauge update timer (100ms = 10 FPS refresh for gauges)
  lv_timer_create(_ui_gauge_update_timer_cb, 100, NULL);
  ESP_LOGI("UI", "Gauge update timer started (100ms interval)");

  // Sync global demo mode state with loaded settings
  ui_set_global_demo_mode(demo_mode_get_enabled());
}

void ui_destroy(void) {
  ui_Screen1_screen_destroy();
  ui_Screen2_screen_destroy();
  ui_Screen3_screen_destroy();
  ui_Screen4_screen_destroy();
  ui_Screen5_screen_destroy();
  ui_Screen6_screen_destroy();
  ui_Screen7_screen_destroy();
  ui_Screen9_screen_destroy();
  ui_Screen10_screen_destroy();
  ui_Screen11_screen_destroy();
  ui_Screen12_screen_destroy();
}

/**
 * @brief Sets the demo mode on or off for all relevant screens.
 *
 * @param enabled true to enable demo mode, false to disable.
 */
void ui_set_global_demo_mode(bool enabled) {
  // Update the data simulation flag
  ui_updates_set_demo_mode(enabled);

  // Call the animation update function for each screen that supports it.
  ui_Screen1_update_animations(enabled);
  ui_Screen2_update_animations(enabled);
  ui_Screen4_update_animations(enabled);
  ui_Screen5_update_animations(enabled);
}

static lv_obj_t *s_unit_popup = NULL;

static void unit_popup_close_cb(lv_event_t *e) {
  if (s_unit_popup) {
    lv_obj_del_async(s_unit_popup);
    s_unit_popup = NULL;
  }
}

static void unit_select_cb(lv_event_t *e) {
  gauge_id_t id = (gauge_id_t)(uintptr_t)lv_event_get_user_data(e);
  lv_obj_t *btn = lv_event_get_target(e);
  gauge_unit_t selected_unit = (gauge_unit_t)(uintptr_t)lv_obj_get_user_data(btn);

  system_settings_t *settings = system_settings_get();
  if (settings) {
    settings->gauge_units[id] = selected_unit;
    system_settings_save(settings);
  }

  // Close popup
  unit_popup_close_cb(NULL);
}

static void ambient_temp_val_cb(lv_event_t *e) {
  int val = (int)(uintptr_t)lv_event_get_user_data(e);
  settings_set_ambient_can_temp((float)val);

  lv_obj_t *btn = lv_event_get_target(e);
  lv_obj_t *row = lv_obj_get_parent(btn);
  uint32_t cnt = lv_obj_get_child_cnt(row);
  for (uint32_t i = 0; i < cnt; i++) {
    lv_obj_t *child = lv_obj_get_child(row, i);
    int child_val = (int)(uintptr_t)lv_obj_get_user_data(child);
    if (child_val == val) {
      lv_obj_set_style_bg_color(child, lv_color_hex(0x00FF88), 0); // Active green
    } else {
      lv_obj_set_style_bg_color(child, lv_color_hex(0x333333), 0); // Dark grey
    }
  }
  ESP_LOGI("UI", "Target Ambient Temp set to %d C", val);
}

static void ambient_temp_send_toggle_cb(lv_event_t *e) {
  lv_obj_t *cb = lv_event_get_target(e);
  bool checked = lv_obj_has_state(cb, LV_STATE_CHECKED);
  settings_set_send_ambient_temp_to_can(checked);
  ESP_LOGI("UI", "Ambient Temp Send to CAN toggled to: %s", checked ? "ON" : "OFF");

  // Toggle visibility of the temperature selector row
  lv_obj_t *temp_row = (lv_obj_t *)lv_obj_get_user_data(cb);
  if (temp_row) {
    if (checked) {
      lv_obj_clear_flag(temp_row, LV_OBJ_FLAG_HIDDEN);
    } else {
      lv_obj_add_flag(temp_row, LV_OBJ_FLAG_HIDDEN);
    }
  }
}

void ui_gauge_click_event_cb(lv_event_t *e) {
  gauge_id_t id = (gauge_id_t)(uintptr_t)lv_event_get_user_data(e);

  if (s_unit_popup) {
    lv_obj_del(s_unit_popup);
    s_unit_popup = NULL;
  }

  // Check what units are available for this gauge
  const char *opts[4] = {NULL};
  gauge_unit_t units[4] = {0};
  int opt_count = 0;

  if (id == GAUGE_MAP || id == GAUGE_BOOST || id == GAUGE_OIL_PRESS || id == GAUGE_FUEL_PRESS || id == GAUGE_BOOST_ACT) {
    opts[0] = "kPa";   units[0] = UNIT_KPA;
    opts[1] = "Bar";   units[1] = UNIT_BAR;
    opts[2] = "PSI";   units[2] = UNIT_PSI;
    opt_count = 3;
  } else if (id == GAUGE_AFR) {
    opts[0] = "Lambda";   units[0] = UNIT_LAMBDA;
    opts[1] = "AFR 14.7"; units[1] = UNIT_AFR;
    opts[2] = "Volts";    units[2] = UNIT_VOLTS;
    opt_count = 3;
  } else if (id == GAUGE_OIL_TEMP || id == GAUGE_WATER_TEMP || id == GAUGE_IAT || id == GAUGE_TRANS_TEMP || id == GAUGE_EGT || id == GAUGE_AMBIENT_TEMP) {
    opts[0] = "Celsius (C)";       units[0] = UNIT_CELSIUS;
    opts[1] = "Fahrenheit (F)";   units[1] = UNIT_FAHRENHEIT;
    opt_count = 2;
  } else if (id == GAUGE_SPEED) {
    opts[0] = "km/h";   units[0] = UNIT_KMH;
    opts[1] = "mph";    units[1] = UNIT_MPH;
    opt_count = 2;
  } else if (id == GAUGE_TCU_REQ || id == GAUGE_TCU_ACT || id == GAUGE_ENG_REQ || id == GAUGE_ENG_ACT || id == GAUGE_LIMIT_TQ) {
    opts[0] = "Newton Meters (Nm)"; units[0] = UNIT_NM;
    opts[1] = "Percent (%)";        units[1] = UNIT_PCT;
    opt_count = 2;
  }

  if (opt_count == 0) return; // No units for this gauge

  // Create popup modal
  lv_obj_t *current_scr = lv_scr_act();
  s_unit_popup = lv_obj_create(current_scr);
  lv_obj_set_size(s_unit_popup, 400, (id == GAUGE_AMBIENT_TEMP) ? 420 : 320);
  lv_obj_center(s_unit_popup);
  lv_obj_set_style_bg_color(s_unit_popup, lv_color_hex(0x1a1a1a), 0);
  lv_obj_set_style_bg_opa(s_unit_popup, LV_OPA_COVER, 0);
  lv_obj_set_style_border_color(s_unit_popup, lv_color_hex(0x00D4FF), 0);
  lv_obj_set_style_border_width(s_unit_popup, 2, 0);
  lv_obj_set_style_radius(s_unit_popup, 15, 0);
  lv_obj_set_style_pad_all(s_unit_popup, 15, 0);
  lv_obj_set_flex_flow(s_unit_popup, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(s_unit_popup, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_set_style_pad_gap(s_unit_popup, 15, 0);

  // Title
  lv_obj_t *title = lv_label_create(s_unit_popup);
  lv_label_set_text(title, "Select Unit");
  lv_obj_set_style_text_color(title, lv_color_white(), 0);
  lv_obj_set_style_text_font(title, &montserrat_20_en_ru, 0);

  // Unit Options
  for (int i = 0; i < opt_count; i++) {
    lv_obj_t *btn = lv_btn_create(s_unit_popup);
    lv_obj_set_size(btn, 280, 44);
    lv_obj_set_style_bg_color(btn, lv_color_hex(0x333333), 0);
    lv_obj_set_style_radius(btn, 8, 0);
    lv_obj_add_event_cb(btn, unit_select_cb, LV_EVENT_CLICKED, (void*)(uintptr_t)id);
    lv_obj_set_user_data(btn, (void*)(uintptr_t)units[i]);

    lv_obj_t *lbl = lv_label_create(btn);
    lv_label_set_text(lbl, opts[i]);
    lv_obj_set_style_text_color(lbl, lv_color_white(), 0);
    lv_obj_center(lbl);
  }

  // Add CAN broadcast toggle checkbox and temp selection for Ambient Temperature Gauge
  if (id == GAUGE_AMBIENT_TEMP) {
    // Create the temp_row container first
    lv_obj_t *temp_row = lv_obj_create(s_unit_popup);
    lv_obj_set_size(temp_row, 365, 48);
    lv_obj_set_flex_flow(temp_row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(temp_row, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_opa(temp_row, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(temp_row, 0, 0);
    lv_obj_set_style_pad_all(temp_row, 0, 0);
    lv_obj_set_style_pad_gap(temp_row, 4, 0);

    float current_target_temp = settings_get_ambient_can_temp();
    int temp_values[] = {5, 10, 15, 20, 25, 30, 35};
    for (int j = 0; j < 7; j++) {
      lv_obj_t *t_btn = lv_btn_create(temp_row);
      lv_obj_set_size(t_btn, 46, 36);
      lv_obj_set_user_data(t_btn, (void*)(uintptr_t)temp_values[j]);
      lv_obj_add_event_cb(t_btn, ambient_temp_val_cb, LV_EVENT_CLICKED, (void*)(uintptr_t)temp_values[j]);
      
      // Determine background color
      if ((int)current_target_temp == temp_values[j]) {
        lv_obj_set_style_bg_color(t_btn, lv_color_hex(0x00FF88), 0); // Active green
      } else {
        lv_obj_set_style_bg_color(t_btn, lv_color_hex(0x333333), 0); // Dark grey
      }
      lv_obj_set_style_radius(t_btn, 8, 0);

      lv_obj_t *t_lbl = lv_label_create(t_btn);
      char t_str[8];
      snprintf(t_str, sizeof(t_str), "+%d", temp_values[j]);
      lv_label_set_text(t_lbl, t_str);
      lv_obj_set_style_text_color(t_lbl, lv_color_white(), 0);
      lv_obj_center(t_lbl);
    }

    // Create the checkbox and link the temp_row in user_data
    lv_obj_t *cb = lv_checkbox_create(s_unit_popup);
    lv_checkbox_set_text(cb, "Send to CAN");
    lv_obj_set_style_text_color(cb, lv_color_white(), 0);
    
    bool is_sending = settings_get_send_ambient_temp_to_can();
    if (is_sending) {
      lv_obj_add_state(cb, LV_STATE_CHECKED);
      lv_obj_clear_flag(temp_row, LV_OBJ_FLAG_HIDDEN);
    } else {
      lv_obj_add_flag(temp_row, LV_OBJ_FLAG_HIDDEN);
    }
    
    lv_obj_set_user_data(cb, temp_row);
    lv_obj_add_event_cb(cb, ambient_temp_send_toggle_cb, LV_EVENT_VALUE_CHANGED, NULL);
  }

  // Cancel Button
  lv_obj_t *cancel_btn = lv_btn_create(s_unit_popup);
  lv_obj_set_size(cancel_btn, 140, 40);
  lv_obj_set_style_bg_color(cancel_btn, lv_color_hex(0xFF3333), 0);
  lv_obj_set_style_radius(cancel_btn, 8, 0);
  lv_obj_add_event_cb(cancel_btn, unit_popup_close_cb, LV_EVENT_CLICKED, NULL);

  lv_obj_t *cancel_lbl = lv_label_create(cancel_btn);
  lv_label_set_text(cancel_lbl, "Cancel");
  lv_obj_set_style_text_color(cancel_lbl, lv_color_white(), 0);
  lv_obj_center(cancel_lbl);
}
