// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11 (migrated to 9.4.0)
// Project name: Westgate Dashboard

#include "ui.h"
#include "esp_log.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"

#include "ui_helpers.h"
#include "ui_layout_manager.h"
#include "ui_screen_manager.h"


// EVENTS
lv_obj_t *ui____initial_actions0;

// TOUCH SCREEN STATE
bool touch_active = true;

///////////////////// TEST LVGL SETTINGS ////////////////////
// NOTE: These checks are disabled for EK79007 display which uses RGB888
// #if LV_COLOR_DEPTH != 16
//     #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's
//     settings"
// #endif
// #if LV_COLOR_16_SWAP !=0
//     #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's
//     settings"
// #endif

///////////////////// SCREENS ////////////////////

void ui_init(void) {
  LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

  lv_disp_t *dispp = lv_disp_get_default();
  ESP_LOGI("UI", "Default display: %p", (void *)dispp);
  if (dispp == NULL) {
    ESP_LOGE("UI", "FATAL: No display registered! ui_init cannot continue.");
    return;
  }
  // Apply theme FIRST (as in old working version) - this was the correct order
  lv_theme_t *theme = lv_theme_default_init(
      dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
      false, LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);

  // Initialize touch screen state
  touch_active = true;

  // Initialize screen manager
  ui_screen_manager_init();

  // Settings are already loaded in main.c, no need to load again
  // settings_load(); // REMOVED: Settings already loaded in main.c

  // Initialize all screens AFTER theme is applied (as in old working version)
  ui_Screen1_screen_init();
  ui_Screen2_screen_init(); // Add Screen2 initialization
  ui_Screen3_screen_init(); // Add Screen3 initialization
  ui_Screen4_screen_init(); // Add Screen4 initialization
  ui_Screen5_screen_init(); // Add Screen5 initialization
  ui_Screen6_screen_init(); // Add Screen6 initialization
  // ui_Screen7_screen_init(); // DISABLED: Snake game causes watchdog
  // ui_Screen8_screen_init(); // Disabled: Causes watchdog timeout in LVGL mask
  // drawing

  ui____initial_actions0 = lv_obj_create(NULL);

  // Initialize unified layout manager and apply initial layout
  ui_layout_manager_init();

  lv_scr_load(ui_Screen1);
}

void ui_destroy(void) {
  ui_Screen1_screen_destroy();
  ui_Screen2_screen_destroy();
  ui_Screen3_screen_destroy();
  ui_Screen4_screen_destroy();
  ui_Screen5_screen_destroy();
  ui_Screen6_screen_destroy();
}

/**
 * @brief Sets the demo mode on or off for all relevant screens.
 *
 * @param enabled true to enable demo mode, false to disable.
 */
void ui_set_global_demo_mode(bool enabled) {
  // Update the data simulation flag
  ui_updates_set_demo_mode(enabled);

  // Call the animation update function for each screen that supports it.
  ui_Screen1_update_animations(enabled);
  ui_Screen2_update_animations(enabled);
  ui_Screen4_update_animations(enabled);
  ui_Screen5_update_animations(enabled);
}
